services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    GimmeBundle\Controller\:
        resource: '../../../GimmeBundle/Controller/*'
        public: true
        tags: ['controller.service_arguments']

    Symfony\Component\HttpKernel\Config\FileLocator:
        arguments:
            $paths:
                - '%kernel.project_dir%/src/GimmeBundle/Resources/assets/javascript/dist/'
                - '%kernel.project_dir%/src/GimmeBundle/Resources/assets/stylesheet/dist/'
