filter:
    paths: ["src/*", "tests/*"]

checks:
    php: true

build:
    environment:
        php: '7.1.12'
        node: 'v6.13.0'
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=clover-file.xml'
                coverage:
                    file: 'clover-file.xml'
                    format: 'clover'
