language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.1

before_install:
  - composer self-update

install:
  - composer install

script:
  - ./vendor/bin/phpunit
